apiVersion: v1
kind: Namespace
metadata:
  name: event-exporter
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: event-exporter
  name: event-exporter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: event-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    namespace: event-exporter
    name: event-exporter
