apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: <YOUR_DOMAIN_NAME>
  # Cert-Manager will put the resulting Secret in the same Kubernetes namespace as the Certificate.
  namespace: microservices-demo-prod
spec:
  # Secret name to create, where the private key and certificate should be stored.
  secretName: <YOUR_DOMAIN_NAME>
  # What Issuer to use for getting the certificate.
  issuerRef:
    name: letsencrypt-nginx-wcard
    kind: Issuer
    group: cert-manager.io
  # Common name to be used on the Certificate.
  commonName: "*.<YOUR_DOMAIN_NAME>"
  # List of DNS subjectAltNames to be set on the Certificate.
  dnsNames:
    - "<YOUR_DOMAIN_NAME>"
    - "*.<YOUR_DOMAIN_NAME>"
